import {
  Dataset,
  CandidateModel,
  ObjectiveWeights,
  EvolutionaryOptimizationRun,
  SinglePredictionExplanation,
  AnomalySummary,
  IntelligenceReport,
  ProblemType,
} from '../types';

const API_BASE = import.meta.env.VITE_API_URL || '';

/**
 * EVOX Unified API Client
 * Connects directly to the genuine Python FastAPI / ML engine.
 * Transparent, verifiable ML without simulated figures.
 */
export const api = {
  /**
   * Health check to ensure Python FastAPI engine is responsive
   */
  async checkHealth(): Promise<{ status: string; engine: string; xgboost_available?: boolean }> {
    try {
      const res = await fetch(`${API_BASE}/api/health`, { method: 'GET' });
      if (res.ok) return await res.json();
    } catch {
      // Backend offline or starting
    }
    return { status: 'OFFLINE', engine: 'Python FastAPI Engine (Waiting for process)' };
  },

  /**
   * Check backend capabilities, including XGBoost status (FIX 3)
   */
  async getCapabilities(): Promise<any> {
    try {
      const res = await fetch(`${API_BASE}/api/capabilities`, { method: 'GET' });
      if (res.ok) return await res.json();
    } catch {
      // Return fallback info
    }
    return {
      success: false,
      xgboost: { supported: false, status: 'UNKNOWN', message: 'Engine checking capability...' },
    };
  },

  /**
   * Fetch genuine synthetic demo dataset generated by Python NumPy/Pandas
   */
  async getDemoDataset(): Promise<Dataset> {
    const res = await fetch(`${API_BASE}/api/demo`, { method: 'GET' });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.detail?.message || err.detail || err.error || 'Failed to fetch demo dataset from Python ML engine.';
      throw new Error(msg);
    }
    const data = await res.json();
    return data.dataset;
  },

  /**
   * Upload and profile raw dataset using genuine Pandas profiling
   */
  async uploadDataset(name: string, rows: Record<string, any>[], fileSize: number): Promise<Dataset> {
    const res = await fetch(`${API_BASE}/api/dataset/upload`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name, rows, fileSize }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.detail?.message || err.detail || err.error || 'Failed to profile dataset in Python engine.';
      throw new Error(msg);
    }
    const data = await res.json();
    return data.dataset;
  },

  /**
   * Train AutoML candidate models via Scikit-Learn and XGBoost
   * Polls background training job status (FIX 7) to provide real progression stages:
   * Loading dataset -> Preprocessing -> Training models -> Optimization -> Explainability -> Finalizing report.
   */
  async trainModels(
    dataset: Dataset,
    problemType: ProblemType,
    targetCol: string,
    onProgress?: (progress: number, step: string) => void
  ): Promise<CandidateModel[]> {
    if (onProgress) {
      onProgress(5, 'Submitting training task to background engine...');
    }

    const res = await fetch(`${API_BASE}/api/train`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        datasetId: dataset.id,
        problemType,
        targetCol,
      }),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.detail?.message || err.detail || err.error || 'Model training failed in Python backend.';
      throw new Error(msg);
    }

    const data = await res.json();

    // Background job polling (FIX 7)
    if (data.job_id) {
      const jobId = data.job_id;
      let isComplete = false;
      let pollAttempts = 0;
      const maxPollAttempts = 300; // 2.5 minutes timeout limit

      while (!isComplete && pollAttempts < maxPollAttempts) {
        pollAttempts++;
        await new Promise((resolve) => setTimeout(resolve, 400));

        const statusRes = await fetch(`${API_BASE}/api/train/${jobId}/status`);
        if (!statusRes.ok) {
          const err = await statusRes.json().catch(() => ({}));
          const msg = err.detail?.message || err.detail || 'Failed to check training status';
          throw new Error(msg);
        }

        const statusData = await statusRes.json();
        const stage = statusData.current_stage || 'Processing';
        const msg = statusData.message || 'Executing stage...';

        if (onProgress) {
          onProgress(statusData.progress || 10, `[${stage}] ${msg}`);
        }

        if (statusData.status === 'completed') {
          isComplete = true;
          return statusData.models || [];
        } else if (statusData.status === 'failed') {
          throw new Error(statusData.error || statusData.message || 'AutoML training failed');
        }
      }

      throw new Error('Training job timed out waiting for completion.');
    }

    if (data.models) {
      if (onProgress) onProgress(100, 'All models fitted and registered in Joblib model store.');
      return data.models;
    }

    throw new Error('No candidate models returned from Python backend.');
  },

  /**
   * Run genuine Evolutionary Genetic Hyperparameter Optimization (FIX 1)
   */
  async runOptimization(datasetId: string, generations = 8): Promise<EvolutionaryOptimizationRun> {
    const res = await fetch(`${API_BASE}/api/optimize`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ datasetId, generations }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.detail?.message || err.detail || err.error || 'Optimization search failed in Python backend.';
      throw new Error(msg);
    }
    const data = await res.json();
    return data.optimization;
  },

  /**
   * Run genuine Optuna TPE Hyperparameter Optimization (FIX 2)
   */
  async runOptunaOptimization(datasetId: string, trials = 10): Promise<EvolutionaryOptimizationRun> {
    const res = await fetch(`${API_BASE}/api/optimize/optuna`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ datasetId, generations: trials }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.detail?.message || err.detail || err.error || 'Optuna study failed in Python backend.';
      throw new Error(msg);
    }
    const data = await res.json();
    return data.optimization;
  },

  /**
   * Detect anomalies with real Scikit-Learn IsolationForest (FIX 10)
   */
  async runAnomalyDetection(dataset: Dataset, rate = 0.05): Promise<AnomalySummary> {
    const res = await fetch(`${API_BASE}/api/anomaly`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ datasetId: dataset.id, contaminationRate: rate }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.detail?.message || err.detail || err.error || 'IsolationForest detection failed in Python backend.';
      throw new Error(msg);
    }
    const data = await res.json();
    return data.anomalies;
  },

  /**
   * Predict and explain single record using fitted model & SHAP (FIX 9 & FIX 11)
   */
  async predict(model: CandidateModel, features: Record<string, any>): Promise<SinglePredictionExplanation> {
    const res = await fetch(`${API_BASE}/api/predict`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ modelId: model.id, features }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.detail?.message || err.detail || err.error || 'Model inference failed in Python backend.';
      throw new Error(msg);
    }
    const data = await res.json();
    return data.prediction;
  },

  /**
   * Generate Intelligence Report from real evaluated results (FIX 12)
   */
  async generateReport(
    dataset: Dataset,
    models: CandidateModel[],
    anomalies: AnomalySummary
  ): Promise<IntelligenceReport> {
    const res = await fetch(`${API_BASE}/api/report/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ dataset, models, anomalies }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.detail?.message || err.detail || err.error || 'Report synthesis failed in Python backend.';
      throw new Error(msg);
    }
    const data = await res.json();
    return data.report;
  },
};
